function [fitresult, gof] = fit_gauss2d(x_pax, y_pax)
%CREATEFIT(X_PAX,Y_PAX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x_pax
%      Y Output: y_pax
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Jan-2024 17:25:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x_pax, y_pax );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [521 12.692 29.2790478675827];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y_pax vs. x_pax', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'x_pax', 'Interpreter', 'none' );
% ylabel( 'y_pax', 'Interpreter', 'none' );
% grid on


